# Generated by Django 5.0.4 on 2024-05-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taskname', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
